# Generated by Django 2.2.3 on 2019-11-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('bookprice', models.FloatField()),
                ('bookqty', models.IntegerField()),
                ('bookauthor', models.CharField(max_length=100)),
                ('bookcate', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y', max_length=10)),
            ],
            options={
                'db_table': 'Book_Info',
            },
        ),
    ]
